name: Java-run-flow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  first-job:
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-java@v2
