name: java-run
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main 
jobs:
  first-job:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - run: java --version
    - run: javac HelloWorld.java
    - run: java HelloWorld      
